version: 0.2
environment_variables:
    plaintext:
        S3_BUCKET: "build.bookinbot.com"
        BUILD_ENV: "prod"
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
            - npm install -g serverless
    build:
        commands:
            - echo Build Angular Code
            - ng build --prod --aot --output-hashing all 
            - echo Copy Build to S3
            - cd serverless
            - serverless client deploy --stage prod
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes