version: 0.2
environment_variables:
    plaintext:
        S3_BUCKET: "build.bookinbot.com"
        BUILD_ENV: "prod"
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
            - npm install -g serverless
            - npm install --save serverless-finch
            - npm install serverless-offline --save-dev
    build:
        commands:
            - echo Check Serverless Version
            - sls --version
            - echo Build Angular Code
            - ng build --prod --aot --output-hashing all 
            - echo Copy Build to S3
            - cd serverless
            - sls client deploy --stage prod
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes