version: 0.2
environment_variables:
    plaintext:
        S3_BUCKET: "build.bookinbot.com"
        BUILD_ENV: "prod"
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install --save-dev @angular/cli@latest
    build:
        commands:
            - echo Starting Angular Build
            - node --version
            - ng --version
            - ng build --prod --aot --output-hashing all 
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes