# serverless.yml
plugins:
  - serverless-finch
  - serverless-domain-manager  
  - serverless-dynamodb-local
  - serverless-offline #serverless-offline needs to be last in the list  
  - serverless-webpack

service: bookinbot-application

custom:
  cognitoPoolArn: ${env:COGNITO_POOL_ARN}
  cognitoAuthorizer:
    arn: ${self:custom.cognitoPoolArn}

  customDomain:
    domainName: api.${env:DOMAIN_NAME}
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true    

  client:
    bucketName: '${self:provider.url}-dist'
    distributionFolder: ../dist 
    indexDocument: index.html 
    errorDocument: index.html 
  tableNameResources: 'bookinbot-resources'    
  tableNameBookings: 'bookinbot-bookings' 
  tableNameShares: 'bookinbot-shares'    
  accessKey: ${env:COGNITO_AWS_ACCESS_KEY}
  secretKey: ${env:COGNITO_AWS_SECRET_KEY}  
  userpoolid: ${env:COGNITO_USER_POOL_ID}  
  dynamodb:
    start:
      migrate: true


provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  url: ${env:DOMAIN_NAME}    
  region: ap-southeast-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["ResourcesDynamoDBTable", "Arn"] }
        - { "Fn::GetAtt": ["BookingsDynamoDBTable", "Arn"] }        
        - { "Fn::GetAtt": ["SharesDynamoDBTable", "Arn"] }        
  environment:
    RESOURCES_TABLE: ${self:custom.tableNameResources}
    BOOKINGS_TABLE: ${self:custom.tableNameBookings}    
    SHARES_TABLE: ${self:custom.tableNameShares}    
    STAGE: ${opt:stage}
    COGNITO_AWS_ACCESS_KEY: ${self:custom.accessKey}   
    COGNITO_AWS_SECRET_KEY: ${self:custom.secretKey} 
    COGNITO_USER_POOL_ID: ${self:custom.userpoolid}       
              
functions:
  process:
      handler: handler.execute
      events: ${file(events.yml):events} 

resources:
  Resources:
    ResourcesDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - 
            AttributeName: ownerid
            AttributeType: S          
          - 
            AttributeName: id
            AttributeType: S
        KeySchema:
          - 
            AttributeName: ownerid
            KeyType: HASH          
          - 
            AttributeName: id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableNameResources}
    BookingsDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - 
            AttributeName: resourceid
            AttributeType: S
          - 
            AttributeName: id
            AttributeType: S            
        KeySchema:
          - 
            AttributeName: resourceid
            KeyType: HASH
          - 
            AttributeName: id
            KeyType: RANGE            
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableNameBookings}
    SharesDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - 
            AttributeName: userid
            AttributeType: S            
          - 
            AttributeName: resourceid
            AttributeType: S
          - 
            AttributeName: id
            AttributeType: S            
        KeySchema:
          - 
            AttributeName: resourceid
            KeyType: HASH
          - 
            AttributeName: id
            KeyType: RANGE            
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableNameShares}
        GlobalSecondaryIndexes:
        - IndexName: shares_user_resources
          KeySchema:
          - AttributeName: userid
            KeyType: HASH
          - AttributeName: resourceid
            KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1       
